cmake_minimum_required(VERSION 3.31)
project(luogu)

set(CMAKE_CXX_STANDARD 20)

add_executable(luogu U300331.cpp
        U300333.cpp
        U300336.cpp
        U300329.cpp
        U301629.cpp
        U301632.cpp
        U306965.cpp
        P1464.cpp
        P1596.cpp
        U303042.cpp
        P1825.cpp
        AT_abc383_c.cpp
        P1588.cpp
        AT_abc405_d.cpp
        U303045.cpp
        P14360.cpp
        P14357.cpp
        U308328.cpp
        U308329.cpp
        P14358.cpp
        U308330.cpp
        U308331.cpp
        P2367.cpp
        AT_abc408_c.cpp
        B4192.cpp
        P5117.cpp
        AT_abc356_c.cpp
        AT_abc367_c.cpp
        B3623.cpp
        U303047.cpp
        U303046.cpp
        P2036.cpp
        P1706.cpp
        U303048.cpp
        B3643.cpp
        T320770.cpp
        T320773.cpp
        T320774.cpp
        T320772.cpp
        T320791.cpp
        U282420.cpp
        AT_abc389_c.cpp
        AT_abc404_C.cpp
        P1330.cpp
        U433472.cpp
        AT_abc270_c.cpp
        B4016.cpp
        AT_abc361_e.cpp
        P11378.cpp
        "atcoder abc 435/AT_abc435_a.cpp"
        "atcoder abc 435/AT_abc435_b.cpp"
        "atcoder abc 435/AT_abc435_c.cpp"
        "atcoder abc 435/AT_abc435_d.cpp"
        "atcoder abc 435/AT_abc435_e.cpp"
        P10722.cpp
        P10109.cpp
        P11962.cpp
        P10378.cpp
        P13016.cpp
        P14076.cpp
        P14077.cpp
        U628622.cpp
        P1144.cpp
        AT_abc376_d.cpp
        U554341.cpp
        U445086.cpp
        "atcoder abc 436/AT_abc436_a.cpp"
        "atcoder abc 436/AT_abc436_b.cpp"
        "atcoder abc 436/AT_abc436_c.cpp"
        "atcoder abc 436/AT_abc436_d.cpp"
        P5663.cpp
        P10723.cpp
        "atcoder abc 437/AT_abc437_A.cpp"
        "atcoder abc 437/AT_abc437_b.cpp"
        "atcoder abc 437/AT_abc437_c.cpp"
        "atcoder abc 437/AT_abc437_d.cpp"
        P1216.cpp
        U509740.cpp
        "atcoder dp/AT_dp_c.cpp"
        AT_abc365_d.cpp
        "atcoder dp/AT_dp_d.cpp"
        U478177.cpp
        U624707.cpp
        P14075.cpp
        P13015.cpp
        P11963.cpp
        "atcoder dp/AT_dp_e.cpp"
        B3644.cpp
        P2712.cpp
        P1807.cpp
        AT_abc238_e.cpp
        P11280.cpp
        AT_abc368_d.cpp
        AT_abc373_d.cpp
        "atcoder abc 438/AT_abc438_a.cpp"
        P3916.cpp
        B3637.cpp
        U522833.cpp
        "atcoder dp/AT_dp_f.cpp"
        AT_abc291_d.cpp
        AT_abc306_d.cpp
        "atcoder dp/AT_dp_a.cpp"
        AT_abc266_d.cpp
        "atcoder abc 439/AT_abc439_a.cpp"
        "atcoder abc 439/AT_abc439_b.cpp"
        "atcoder abc 439/AT_abc439_c.cpp"
        "atcoder abc 439/AT_abc439_d.cpp"
        "atcoder abc 439/AT_abc439_e.cpp"
        "atcoder dp/AT_dp_h.cpp"
        "atcoder dp/AT_dp_b.cpp"
        U525270.cpp
        B3637.cpp
        T376044.cpp
        T370645.cpp
        T376050.cpp
        T376052.cpp
        P1077.cpp
        P1507.cpp
        T376048.cpp
        T376053.cpp
        T376047.cpp
        T376051.cpp
        U409376.cpp
        P1164.cpp
        P1616.cpp
        P2725.cpp
        P2722.cpp
        AT_abc364_e.cpp
        P1049.cpp
        P1679.cpp
        P1832.cpp
        P1926.cpp
        P1575.cpp
        AT_abc321_f.cpp
        P3371.cpp
        P3385.cpp
        U447511.cpp
        P1339.cpp
        P1828.cpp
        P4141.cpp
        U447845.cpp
        header.h
        B3647.cpp
        B3611.cpp
        P2419.cpp
        P6175.cpp
        AT_abc243_e.cpp
        P1119.cpp
        AT_abc375_f.cpp
        P3905.cpp
        normal_dijkstra.cpp
        P4779.cpp
        P3003.cpp
        U632129.cpp
        AT_abc395_e.cpp
        AT_abc277_e.cpp
        P4568.cpp
        P2865.cpp
        P3008.cpp
        AT_abc164_e.cpp
        AT_abc305_f.cpp
        AT_abc303_e.cpp
        AT_abc354_c.cpp
        AT_abc364_c.cpp
        AT_abc370_c.cpp
        U524631.cpp
        U524656.cpp
        P2249.cpp
        U447586.cpp
        P14920.cpp
        huffman.cpp
        grey_code.cpp
        P1352.cpp
        P1122.cpp
        P14919.cpp
        AT_abc448_d.cpp
        P11248.cpp
        P11375.cpp
        P11246.cpp
        P10377.cpp
        P10250.cpp
        P10262.cpp
        P15801.cpp
        P2016.cpp
        "atcoder dp/AT_dp_p.cpp"
        P2458.cpp
        U510996.cpp
        P3478.cpp
        P2986.cpp
        P10962.cpp
        P3047.cpp
        P10974.cpp
        "atcoder dp/AT_dp_i.cpp"
        "atcoder dp/AT_dp_j.cpp"
        codeforce/CF104396F.cpp
        codeforce/CF24D.cpp
        UVA11021.cpp
        P2014.cpp
        P1273.cpp
        P2015.cpp
        P9414.cpp
        P1131.cpp
        AT_abc239_e.cpp
        AT_abc259_f.cpp
        P13085.cpp
        "atcoder dp/AT_dp_s.cpp"
        U584945.cpp
        T322620.cpp
        AT_abc170_e.cpp
        AT_abc338_c.cpp
        AT_abc278_d.cpp
        T419007.cpp
        AT_abc026_c.cpp
        AT_abc040_c.cpp
        AT_abc129_c.cpp
        AT_abc168_d.cpp
        AT_abc175_e.cpp
        AT_abc211_d.cpp
        AT_abc212_d.cpp
        AT_abc217_d.cpp
        AT_abc226_b.cpp
        AT_abc231_d.cpp
        AT_abc240_c.cpp
        AT_abc406_d.cpp
        AT_abc392_e.cpp
        AT_abc264_f.cpp
        AT_abc248_f.cpp
        AT_abc289_d.cpp
        AT_abc380_e.cpp
        AT_abc375_e.cpp
        AT_abc271_d.cpp
        AT_abc350_d.cpp
        AT_abc399_c.cpp
        AT_abc417_b.cpp
        AT_abc417_c.cpp
        AT_abc420_e.cpp
        AT_abc434_d.cpp
        AT_abc453_c.cpp
        AT_abc462_d.cpp
        B3609.cpp
        B3616.cpp
        B3642.cpp
        B3873.cpp
        B3874.cpp
        P1111.cpp
        P1220.cpp
        P1262.cpp
        P1396.cpp
        P1918.cpp
        P4124.cpp
        P3119.cpp
        P1836.cpp
        P2863.cpp
        P4387.cpp
        P1775.cpp
        P2106.cpp
        P3416.cpp
        P2860.cpp
        P1955.cpp
        P6121.cpp
        P4170.cpp
        P2602.cpp
        P3388.cpp
        P3367.cpp
        P4999.cpp
        P3387.cpp
        P2812.cpp
        P2858.cpp
        P1879.cpp
        P7414.cpp
        P5250.cpp
        P1880.cpp
        P2334.cpp
        P8435.cpp
        P9325.cpp
        P9424.cpp
        P10108.cpp
        P10376.cpp
        P10447.cpp
        P10522.cpp
        P10721.cpp
        P11227.cpp
        P11247.cpp
        P11376.cpp
        P15800.cpp
        P17012.cpp
        P17013.cpp
        P17014.cpp
        P17015.cpp
        T103481.cpp
        T397159.cpp
        T561330.cpp
        T777953.cpp
        T777956.cpp
        U300311.cpp
        U303050.cpp
        U443473.cpp
        U448576.cpp
        U477933.cpp
        U454030.cpp
        U478141.cpp
        U478183.cpp
        U479667.cpp
        U510626.cpp
        U522972.cpp
        U525297.cpp
        U447661.cpp
        AT_abc371_d.cpp
        AT_abc360_d.cpp
        P1083.cpp
        AT_abc388_e.cpp
        P3853.cpp
        P2440.cpp
        AT_abc365_c.cpp
        T354984.cpp
        P1577.cpp
        P1542.cpp
        P3743.cpp
        P1842.cpp
        P3817.cpp
        P1209.cpp
        P1056.cpp
        U449287.cpp
        P1168.cpp
        P2949.cpp
        P4053.cpp
        P2107.cpp
        P3093.cpp
        P16789.cpp
        P8769.cpp
        P3545.cpp
        AT_abc214_e.cpp
        P0426.cpp
        P1196.cpp
        AT_abc229_e.cpp
        AT_abc264_e.cpp
        AT_arc085_b.cpp
        AT_abc125_d.cpp
        AT_abc149_d.cpp
        AT_abc140_d.cpp
        P3366.cpp
        P1195.cpp
        P1550.cpp
        P1991.cpp
        prim.cpp
        P10110.cpp
        P15803.cpp
        P11249.cpp
        P2916.cpp
        AT_abc352_e.cpp
        AT_abc312_d.cpp
        P1226.cpp
        P3197.cpp
        P17459.cpp
        P17460.cpp
        P17461.cpp
        P17458.cpp
        P17457.cpp
        P10265.cpp
        P11964.cpp
        P1137.cpp
        T826737.cpp
        P2365.cpp
        AT_abc251_e.cpp
        T825265.cpp
        T825273.cpp
        T826742.cpp
        T826741.cpp
        T825257.cpp
        P2347.cpp
)
